---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Testing and Linting
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testing
        run: |
          docker-compose -f docker-compose-deploy.yml build api
          docker-compose run --rm api sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Linting
        run: docker-compose run --rm api sh -c "flake8"
